export const BINDING_LABELS: Record<number, string> = {
  1: "Binds when picked up",
  2: "Binds when equipped",
  3: "Binds when used",
};

export const INVENTORY_TYPE_LABELS: Record<number, string> = {
  1: "Head",
  10: "Hands",
  11: "Finger",
  12: "Trinket",
  13: "One-Hand",
  14: "Shield",
  15: "Ranged",
  16: "Back",
  17: "Two-Hand",
  18: "Bag",
  19: "Tabard",
  2: "Neck",
  20: "Robe",
  21: "Main Hand",
  22: "Off Hand",
  23: "Held In Off-Hand",
  25: "Thrown",
  26: "Ranged",
  3: "Shoulder",
  4: "Shirt",
  5: "Chest",
  6: "Waist",
  7: "Legs",
  8: "Feet",
  9: "Wrist",
};

export const STAT_NAMES: Record<number, string> = {
  0: "Mana",
  1: "Health",
  3: "Agility",
  32: "Critical Strike",
  35: "Resilience",
  36: "Haste",
  37: "Expertise",
  4: "Strength",
  40: "Versatility",
  49: "Mastery",
  5: "Intellect",
  57: "PvP Power",
  6: "Spirit",
  61: "Versatility",
  7: "Stamina",
  71: "Agility or Strength or Intellect",
  72: "Agility or Strength",
  73: "Agility or Intellect",
  74: "Strength or Intellect",
  91: "Avoidance",
  93: "Leech",
  94: "Speed",
};
