import type { HookEntry } from "./hook-registry-types";

import {
  UseClassDemo,
  UseClassListDemo,
  UseGlobalColorsDemo,
} from "./demos-classes";
import {
  UseItemDemo,
  UseItemScalingDemo,
  UseItemsDemo,
  UseItemSearchDemo,
  UseItemSummariesDemo,
  UseItemSummaryDemo,
  UseResolvedItemDemo,
} from "./demos-items";
import { UseJournalListDemo } from "./demos-journal";
import { UseSpecDemo, UseSpecListDemo, UseSpecTraitsDemo } from "./demos-specs";
import {
  UseSpellDemo,
  UseSpellsDemo,
  UseSpellSearchDemo,
  UseSpellSummaryDemo,
} from "./demos-spells";

const GAME_DATA = "@/lib/game-data";
const SERVICES = "@/lib/query/services";

export const HOOK_REGISTRY: HookEntry[] = [
  {
    Demo: UseItemDemo,
    id: "use-item",
    importPath: GAME_DATA,
    kind: "single",
    name: "useItem",
    returns: "QueryResult",
    returnType: "Item",
    signature: "(id: number) => QueryResult<Item>",
    source: "game-data",
  },
  {
    Demo: UseItemSummaryDemo,
    id: "use-item-summary",
    importPath: GAME_DATA,
    kind: "single",
    name: "useItemSummary",
    returns: "QueryResult",
    returnType: "ItemSummary",
    signature: "(id: number) => QueryResult<ItemSummary>",
    source: "game-data",
  },
  {
    Demo: UseSpellDemo,
    id: "use-spell",
    importPath: GAME_DATA,
    kind: "single",
    name: "useSpell",
    returns: "QueryResult",
    returnType: "Spell",
    signature: "(id: number) => QueryResult<Spell>",
    source: "game-data",
  },
  {
    Demo: UseSpellSummaryDemo,
    id: "use-spell-summary",
    importPath: GAME_DATA,
    kind: "single",
    name: "useSpellSummary",
    returns: "QueryResult",
    returnType: "SpellSummary",
    signature: "(id: number) => QueryResult<SpellSummary>",
    source: "game-data",
  },
  {
    Demo: UseSpecDemo,
    id: "use-spec",
    importPath: GAME_DATA,
    kind: "single",
    name: "useSpec",
    returns: "QueryResult",
    returnType: "SpecRow",
    signature: "(id: number) => QueryResult<SpecRow>",
    source: "game-data",
  },
  {
    Demo: UseClassDemo,
    id: "use-class",
    importPath: GAME_DATA,
    kind: "single",
    name: "useClass",
    returns: "QueryResult",
    returnType: "ClassRow",
    signature: "(id: number) => QueryResult<ClassRow>",
    source: "game-data",
  },
  {
    Demo: UseSpecTraitsDemo,
    id: "use-spec-traits",
    importPath: GAME_DATA,
    kind: "single",
    name: "useSpecTraits",
    returns: "QueryResult",
    returnType: "SpecTraitsRow",
    signature: "(specId: number) => QueryResult<SpecTraitsRow>",
    source: "game-data",
  },
  {
    Demo: UseItemsDemo,
    id: "use-items",
    importPath: GAME_DATA,
    kind: "list",
    name: "useItems",
    returns: "QueryListResult",
    returnType: "Item",
    signature: "(ids: number[]) => QueryListResult<Item>",
    source: "game-data",
  },
  {
    Demo: UseItemSummariesDemo,
    id: "use-item-summaries",
    importPath: GAME_DATA,
    kind: "list",
    name: "useItemSummaries",
    returns: "QueryListResult",
    returnType: "ItemSummary",
    signature: "(ids: number[]) => QueryListResult<ItemSummary>",
    source: "game-data",
  },
  {
    Demo: UseSpellsDemo,
    id: "use-spells",
    importPath: GAME_DATA,
    kind: "list",
    name: "useSpells",
    returns: "QueryListResult",
    returnType: "Spell",
    signature: "(ids: number[]) => QueryListResult<Spell>",
    source: "game-data",
  },
  {
    Demo: UseSpecListDemo,
    id: "use-spec-list",
    importPath: GAME_DATA,
    kind: "list",
    name: "useSpecList",
    returns: "QueryListResult",
    returnType: "SpecRow",
    signature: "() => QueryListResult<SpecRow>",
    source: "game-data",
  },
  {
    Demo: UseClassListDemo,
    id: "use-class-list",
    importPath: GAME_DATA,
    kind: "list",
    name: "useClassList",
    returns: "QueryListResult",
    returnType: "ClassRow",
    signature: "() => QueryListResult<ClassRow>",
    source: "game-data",
  },
  {
    Demo: UseJournalListDemo,
    id: "use-journal-list",
    importPath: GAME_DATA,
    kind: "list",
    name: "useJournalList",
    returns: "QueryListResult",
    returnType: "JournalInstance",
    signature: '(kind: "dungeon" | "raid") => QueryListResult<JournalInstance>',
    source: "game-data",
  },
  {
    Demo: UseGlobalColorsDemo,
    id: "use-global-colors",
    importPath: GAME_DATA,
    kind: "global",
    name: "useGlobalColors",
    returns: "QueryListResult",
    returnType: "GlobalColorRow",
    signature: "() => QueryListResult<GlobalColorRow>",
    source: "game-data",
  },
  {
    Demo: UseItemSearchDemo,
    id: "use-item-search",
    importPath: SERVICES,
    kind: "search",
    name: "useItemSearch",
    returns: "QueryListResult",
    returnType: "ItemSearchResult",
    signature: "(query: string) => QueryListResult<ItemSearchResult>",
    source: "react-query",
  },
  {
    Demo: UseSpellSearchDemo,
    id: "use-spell-search",
    importPath: SERVICES,
    kind: "search",
    name: "useSpellSearch",
    returns: "QueryListResult",
    returnType: "SpellSearchResult",
    signature: "(query: string) => QueryListResult<SpellSearchResult>",
    source: "react-query",
  },
  {
    Demo: UseResolvedItemDemo,
    id: "use-resolved-item",
    importPath: GAME_DATA,
    kind: "derived",
    name: "useResolvedItem",
    returns: "QueryResult",
    returnType: "ResolvedItem",
    signature:
      "(item: Item | undefined, bonusIds: number[]) => QueryResult<ResolvedItem>",
    source: "game-data",
  },
  {
    Demo: UseItemScalingDemo,
    id: "use-item-scaling",
    importPath: GAME_DATA,
    kind: "derived",
    name: "useItemScaling",
    returns: "QueryResult",
    returnType: "ItemScalingData",
    signature: "(bonusIds: number[]) => QueryResult<ItemScalingData>",
    source: "game-data",
  },
];
