// @generated by tablegen from the Rust snapshot registry (crates/cli) -- do not edit by hand.

export type BulkTable = {
  readonly key: readonly [string, ...string[]];
  readonly name: string;
};

export const BULK_TABLES = [
  {
    key: ["id"],
    name: "curve_points",
  },
  {
    key: ["id"],
    name: "curves",
  },
  {
    key: ["id"],
    name: "item_bonuses",
  },
  {
    key: ["id"],
    name: "rand_prop_points",
  },
  {
    key: ["id"],
    name: "item_scaling_configs",
  },
  {
    key: ["id"],
    name: "item_offset_curves",
  },
  {
    key: ["id"],
    name: "item_squish_eras",
  },
  {
    key: ["level"],
    name: "combat_ratings",
  },
  {
    key: ["item_level"],
    name: "combat_ratings_mult_by_ilvl",
  },
  {
    key: ["level"],
    name: "hp_per_sta",
  },
  {
    key: ["level"],
    name: "spell_scaling",
  },
  {
    key: ["item_id", "source_kind", "difficulty_key"],
    name: "item_drop_scaling",
  },
  {
    key: ["spec_id"],
    name: "specs_traits",
  },
  {
    key: ["expansion_id", "system"],
    name: "expansion_traits",
  },
  {
    key: ["id"],
    name: "journal_instances",
  },
  {
    key: ["id"],
    name: "global_colors",
  },
  {
    key: ["id"],
    name: "specs",
  },
  {
    key: ["id"],
    name: "power_types",
  },
  {
    key: ["id"],
    name: "classes",
  },
] as const satisfies readonly BulkTable[];

export type BulkTableName = (typeof BULK_TABLES)[number]["name"];
