// @generated by tablegen from the DataResolver trait (crates/engine-ports) -- do not edit by hand.

export type GameDataResolver = {
  getChallengeModeHealth(keystoneLevel: number): Promise<unknown>;
  getContentTuning(contentTuningId: number): Promise<unknown>;
  getContentTuningXDifficulty(contentTuningId: number): Promise<unknown>;
  getContentTuningXExpected(contentTuningId: number): Promise<unknown>;
  getCreature(creatureId: number): Promise<unknown>;
  getCreatureDifficulties(creatureId: number): Promise<unknown>;
  getEnchantment(enchantmentId: number): Promise<unknown>;
  getExpansionTraitTree(expansionId: number, system: string): Promise<unknown>;
  getExpectedStatMod(expectedStatModId: number): Promise<unknown>;
  getExpectedStats(expansionId: number, lvl: number): Promise<unknown>;
  getItem(itemId: number): Promise<unknown>;
  getItemDamageScaling(itemLevel: number, weaponType: string): Promise<unknown>;
  getPowerTypes(): Promise<unknown>;
  getRotationScript(rotationId: string): Promise<unknown>;
  getScalingData(): Promise<unknown>;
  getSpec(specId: number): Promise<unknown>;
  getSpell(spellId: number): Promise<unknown>;
  getTraitTree(specId: number): Promise<unknown>;
};
