export const ENV_VARS = {
  APP_HOST: "NEXT_PUBLIC_APP_HOST",
  APP_URL: "NEXT_PUBLIC_APP_URL",
  BUNNY_STREAM_LIBRARY_ID: "NEXT_PUBLIC_BUNNY_STREAM_LIBRARY_ID",
  CENTRIFUGO_URL: "NEXT_PUBLIC_CENTRIFUGO_URL",
  CF_BEACON_TOKEN: "NEXT_PUBLIC_CF_BEACON_TOKEN",
  CURSEFORGE_MOD_ID: "NEXT_PUBLIC_CURSEFORGE_MOD_ID",
  CURSEFORGE_SLUG: "NEXT_PUBLIC_CURSEFORGE_SLUG",
  IMAGE_ZONE: "NEXT_PUBLIC_IMAGE_ZONE",
  LANDING_HOST: "NEXT_PUBLIC_LANDING_HOST",
  LANDING_URL: "NEXT_PUBLIC_LANDING_URL",
  OG_URL: "NEXT_PUBLIC_OG_URL",
  PADDLE_CLIENT_TOKEN: "NEXT_PUBLIC_PADDLE_CLIENT_TOKEN",
  PADDLE_ENV: "NEXT_PUBLIC_PADDLE_ENV",
  PADDLE_PRICE_BOOST_PACK: "NEXT_PUBLIC_PADDLE_PRICE_BOOST_PACK",
  PADDLE_PRICE_GUILD_SLOT: "NEXT_PUBLIC_PADDLE_PRICE_GUILD_SLOT",
  PADDLE_PRICE_INDIVIDUAL: "NEXT_PUBLIC_PADDLE_PRICE_INDIVIDUAL",
  SENTINEL_URL: "NEXT_PUBLIC_SENTINEL_URL",
  SUPABASE_PUBLISHABLE_KEY: "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
  SUPABASE_URL: "NEXT_PUBLIC_SUPABASE_URL",
  TURNSTILE_SITE_KEY: "NEXT_PUBLIC_TURNSTILE_SITE_KEY",
} as const;

export type EnvKey = keyof typeof ENV_VARS;

export function assertEnv(keys: readonly EnvKey[]): void {
  if (typeof window !== "undefined") {
    return;
  }

  const missing = keys.filter((k) => !process.env[ENV_VARS[k]]);

  if (missing.length > 0) {
    throw new Error(
      `Missing env: ${missing.map((k) => ENV_VARS[k]).join(", ")}`,
    );
  }
}

export const env = {
  APP_HOST: process.env.NEXT_PUBLIC_APP_HOST!,
  APP_URL: process.env.NEXT_PUBLIC_APP_URL!,
  BUNNY_STREAM_LIBRARY_ID: process.env.NEXT_PUBLIC_BUNNY_STREAM_LIBRARY_ID!,
  CENTRIFUGO_URL: process.env.NEXT_PUBLIC_CENTRIFUGO_URL!,
  CF_BEACON_TOKEN: process.env.NEXT_PUBLIC_CF_BEACON_TOKEN!,
  CURSEFORGE_MOD_ID: process.env.NEXT_PUBLIC_CURSEFORGE_MOD_ID!,
  CURSEFORGE_SLUG: process.env.NEXT_PUBLIC_CURSEFORGE_SLUG!,
  DEPLOYMENT_SHA: process.env.NEXT_PUBLIC_DEPLOYMENT_SHA,
  DEPLOYMENT_URL: process.env.NEXT_PUBLIC_DEPLOYMENT_URL,
  DISCORD_URL: `${process.env.NEXT_PUBLIC_LANDING_URL}/go/discord`,
  IMAGE_ZONE: process.env.NEXT_PUBLIC_IMAGE_ZONE!,
  LANDING_HOST: process.env.NEXT_PUBLIC_LANDING_HOST!,
  LANDING_URL: process.env.NEXT_PUBLIC_LANDING_URL!,
  OG_URL: process.env.NEXT_PUBLIC_OG_URL!,
  PADDLE_CLIENT_TOKEN: process.env.NEXT_PUBLIC_PADDLE_CLIENT_TOKEN!,
  PADDLE_ENV: process.env.NEXT_PUBLIC_PADDLE_ENV as "sandbox" | "production",
  PADDLE_PRICE_BOOST_PACK: process.env.NEXT_PUBLIC_PADDLE_PRICE_BOOST_PACK!,
  PADDLE_PRICE_GUILD_SLOT: process.env.NEXT_PUBLIC_PADDLE_PRICE_GUILD_SLOT!,
  PADDLE_PRICE_INDIVIDUAL: process.env.NEXT_PUBLIC_PADDLE_PRICE_INDIVIDUAL!,
  SENTINEL_URL: process.env.NEXT_PUBLIC_SENTINEL_URL!,
  SUPABASE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,
  SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL!,
  TURNSTILE_SITE_KEY: process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY!,
} as const;
