name: CI

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  run:
    name: Run
    uses: wowlabdev/web/.github/workflows/ci-run.yml@main
